case "$(uname -s)" in
  Linux|CYGWIN*|MINGW32*|MSYS*)
    alias ls='ls --color=auto --group-directories-first'
    alias diary='eval $EDITOR `date --date="6 hours ago" +"%Y-%m-%d"`'
    ;;
  FreeBSD)
    alias diary='eval $EDITOR `date -j -v-6H +"%Y-%m-%d"`'
    ;;
esac

alias shot='scrot -d 2 -cs $HOME/media/images/screenshots/%Y-%m-%d_%H%M%S_$HOSTNAME.png'
