" Vundle
set nocompatible
filetype off

set rtp+=~/.vim/vundle/
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

Plugin 'scrooloose/nerdtree'
Plugin 'airblade/vim-gitgutter'

call vundle#end()
filetype plugin indent on

" Personal
set backspace=indent,eol,start
syntax on
set number
set tabstop=2
set shiftwidth=2
set expandtab
set list
set listchars=tab:>-,trail:.,extends:>,precedes:<
set mouse=a

set t_Co=256
colorscheme industry

map <buffer> <silent> k gk
map <buffer> <silent> j gj
map <buffer> <silent> <Up> gk
map <buffer> <silent> <Down> gj

command Date put!=strftime('%c')

