#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources
if [ -d ~/.Xresources.d  ]; then
    for f in ~/.Xresources.d/*; do
        [ -x "$f" ] && xrdb -merge "$f"
    done
    unset f
fi

setxkbmap pl
xset r rate 250 30

[[ `hostname` == 'yendi' ]] && export GDK_BACKEND=x11 && exec gnome-session
[[ `hostname` == 'tournesol' ]] && exec mate-session
[[ `hostname` == 'sunjammer' ]] && exec i3
