#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

[[ -f ~/.config/Xresources ]] && xrdb -merge -I $HOME ~/.config/Xresources

setxkbmap pl

xset r rate 250 30

if [[ `hostname` == sunjammer ]]; then
    exec i3
elif [[ `hostname` == tournesol ]]; then
    exec gnome-session
elif [[ `hostname` == yendi ]]; then
    exec mate-session
fi
