#
# ~/.bashrc
#

shopt -s extglob

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
#PS1='[\u@\h \W]\$ '

export PATH=$PATH:~/scripts/bin:~/.gem/ruby/2.3.0/bin
export PYTHONPATH=~/scripts/lib
export XDG_CONFIG_HOME="$HOME/.config"
export VDPAU_OSD=1

export EDITOR=vim
export LSCOLORS="ExGxFxdxCxDxDxhbadExEx"
export CLICOLOR="YES"
export PS1="[\u\[\033[1;31m\]@\[\033[0m\]\h]\[\033[1;31m\]:\[\033[0m\]<\w>\[\033[1;31m\]\$ \[\033[0m\]"

